name: gaussian_splatting
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pytorch>=2.0
  - torchvision>=0.15
  - torchaudio>=2.0
  - pytorch-cuda=12.1
  - plyfile
  - tqdm
  - numpy
  - scipy
  - pillow
  - opencv
  - pip
  - pip:
    - opencv-python
    - joblib
    - matplotlib
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
    - submodules/fused-ssim